# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-15 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20190415_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='couse_nums',
            new_name='course_nums',
        ),
    ]
