# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=10, verbose_name='学习时长(分钟数)'),
        ),
    ]
